services:
  - type: web
    name: finance-project-backend
    env: docker
    plan: free
    rootDir: backend
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "8000"