services:
  - type: web
    name: finance-project-backend
    env: docker
    plan: free
    rootDir: backend
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "8000"
      - key: DATABASE_URL
        value: postgresql://postgres.qniwjycqhchdltesmykr:neDwpDhae7If1noY@aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://finsight-nine-beta.vercel.app